### ISSUE TITLE
[Feature Request] Add support for ICEPAC

### ISSUE THREAD

**Issue by carchard** [jawatson/voacapl#6]
This is a fantastic repository that provides a significant capability on linux. However, it does not provide an equivalent to Icepacw.exe which is provided from the windows VOACAP downloads (see line 51 in `./src/voacapw/batch.for` where the call is commented out).

https://github.com/jawatson/voacapl/blob/6861fbad041ff7a56b8875c735c9242c81a94320/src/voacapw/batch.for#L51

Is there any intention to eventually provide icepac support?

**Comment by jawatson** [comment]
Thanks for your interest.  The 'ccc' comments are present in the original windows code provided by Greg.  voacap is built on icepac, see [voacap.com](https://www.voacap.com/cappac.html) for some history.  I currently don't have any plans to work on icepac, or the associated rec533 implementation.
